### ISSUE TITLE
AttributeError("'FakeSelector' object has no attribute 'is_ready_for_command'").

### ISSUE THREAD

**Issue by slyboots** [cunla/fakeredis-py#106]
**Describe the bug**
Add the code you are trying to run, the stacktrace you are getting and anything else that might help.
After instantiating a FakeStrictRedis any calls to the command functions such as `get` raise an AttributeError.

After spending a long time in `pdb` I believe that I have found the issue (links to relevant parts of library code):

- The [`FakeSelector`](https://github.com/cunla/fakeredis-py/blob/v2.3.0/fakeredis/_helpers.py#L212) class inherits from `object`, but implements the `check_is_ready_for_command` method from redis-py's [`BaseSelector`](https://github.com/redis/redis-py/blob/3.2.1/redis/selector.py#L55). It __does not__ implement the `is_ready_for_command` method
- The [`FakeConnection`](https://github.com/cunla/fakeredis-py/blob/v2.3.0/fakeredis/_server.py) class inherits from `redis.Connection`. In redis-py 3.2.X [`Connection.is_ready_for_command`](https://github.com/redis/redis-py/blob/3.2.1/redis/connection.py#L632) calls `is_ready_for_command` on the selector
- This blows up in fakeredis-py because that method doesnt exist on `FakeSelector`
 
**To Reproduce**
1. install redis-py 3.2.1
2. install fakeredis-py 2.3.0
3. `python -c 'import fakeredis as FR; FR.FakeStrictRedis(version=6).get("test")'`
4. See error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1264, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 999, in get_connection
    if not connection.is_ready_for_command():
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 632, in is_ready_for_command
    return self._selector.is_ready_for_command()
AttributeError: 'FakeSelector' object has no attribute 'is_ready_for_command'
```

**Expected behavior**
I guess I expect this to not blow up?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker linux
 - python version: 3.8
 - redis-py version: 3.2.1
 - cant include the full requirements.txt because it's a work project. I redacted a few private packages. The problem remains even if I uninstall those private packages though.
```
# Flask
Flask==0.10.1
Jinja2==2.7.2
Werkzeug==0.14.1
MarkupSafe==2.0.1
itsdangerous==2.0.1
# Flask Extensions
Flask-SQLAlchemy==1.0
Flask-Assets==0.9
Frozen-Flask==0.11
Flask-Cache==0.13.1
Flask-Script==2.0.5
flask-webpack-loader==0.0.4
# Services
gunicorn==19.9.0
SQLAlchemy==0.9.3
redis==3.2.1
celery==4.3.0
# Other Libraries
PyYAML==3.13
oauthlib==2.0.3
requests-oauthlib==0.8.0
# Syntax Compression
jsmin==2.0.9
cssmin==0.2.0
# Sentry
raven==6.9.0
blinker==1.3
newrelic==4.2.0.100
arrow==0.12.1
# Testing, etc.
freezegun==0.3.15
pytest==3.0.2
pytest-cov==2.3.1
tox==2.9.1
vcrpy==4.2.1
fakeredis==2.3.0
# Dependency conflict hell
vine==1.3.0
```

**Additional context**

A comment I noticed inside of the [FakeServer code](https://github.com/cunla/fakeredis-py/blob/v2.3.0/fakeredis/_server.py#L59) mentions the `FakeSelector` class inheriting from a stub BaseConnection that doesnt implement `can_read`. Near that comment is a block of code that specially handles the case for FakeSelector.

Im guessing fakeredis probably needs similar special case handling added for the `is_ready_for_command` method like was done there.

After looking at redis-py's implementation, maybe something like:

```python
class FakeConnection(redis.Connection):
    ...
    def is_ready_for_command(self, timeout=0):
        return self._selector.check_is_ready_for_command(timeout)

```

---

tested the above change and it works!:

```python
>>> import fakeredis as FR
>>> r=FR.FakeStrictRedis(version=6)
>>> r.set("test", 1)
>>> print(r.get("test"))
b'1'
```

**Comment by cunla** [comment]
I can not replicate this behavior. I tried:
```
    def test_set_and_get(self):
        r = fakeredis.FakeStrictRedis(version=6)
        r.set('foo', 'bar')
        assert r.get('foo') == b'bar'```
