### ISSUE TITLE
Type issues in Pyright

### ISSUE THREAD

**Issue by Meemaw** [cunla/fakeredis-py#115]
**Describe the bug**
After upgrading to the latest version, we are seeing the following linter (pyright) errors: 

```sh
error: "FakeRedis" is not exported from module "fakeredis"
Import from "fakeredis._server" instead (reportPrivateImportUsage)
```

**Comment by cunla** [comment]
Can you please provide the failing code snippet?

**Comment by Meemaw** [comment]
@cunla https://github.com/cunla/fakeredis-py/pull/116 should fix it.

**Comment by cunla** [comment]
I am not able to replicate this error.
