### ISSUE TITLE
Broken 'json.set' command in v2.6.0+

### ISSUE THREAD

**Issue by kchonka** [cunla/fakeredis-py#119]
Using fakeredis for testing a redis instance. I am patching Redis with an instance of FakeRedis, and getting this error: `redis.exceptions.ResponseError: unknown command 'json.set'`

The call to the cluster is being made in this way: `r.json().set(key, Path.root_path(), value)`

Note this is only showing up in versions > 2.5.0. I see updates were made for JSON support in v2.6.0 and v2.7.0 - there may have been some breaking changes. 

Trace:
`  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/redis/commands/json/commands.py", line 250, in set
    return self.execute_command("JSON.SET", *pieces)`
   `  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/redis/client.py", line 1258, in execute_command
    return conn.retry.call_with_retry(`
`  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()`
`  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/redis/client.py", line 1235, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)`
`  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/redis/client.py", line 1275, in parse_response
    response = connection.read_response()`
`  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/fakeredis/_server.py", line 82, in read_response
    raise response`
`redis.exceptions.ResponseError: unknown command 'json.set'`

Here is a small sample that will trigger the error in v2.60 & 2.7.0:

`from fakeredis import FakeStrictRedis`
`from redis.commands.json.path import Path`
`r = FakeStrictRedis()`
`r.json().set('fdsfsd', Path.root_path(), 'sdfsdf')`

**Comment by cunla** [comment]
Do you have jsonpath_ng installed?

**Comment by kchonka** [comment]
@cunla I have a `jsonpath-ng` installed, not `jsonpath_ng`. Not sure if that's a typo.

I installed via `pip install fakeredis[json]`

**Comment by cunla** [comment]
Yeah, typo on my part. Should have been jsonpath-ng.
Can you write the output of pip freeze here?

**Comment by cunla** [comment]
Also, if you run

```

from fakeredis._commands import SUPPORTED_COMMANDS

print(SUPPORTED_COMMANDS)
```
What do you get?

**Comment by cunla** [comment]
Hi, I managed to replicate. I will submit a fix today

**Comment by kchonka** [comment]
Thanks for the fix! 👍
