### ISSUE TITLE
Support for ZRANGE command with BYLEX arg

### ISSUE THREAD

**Issue by kchonka** [cunla/fakeredis-py#123]
It looks like there is support for ZRANGE https://redis.io/commands/zrange/, but not with the BYLEX=True arg. What I'm trying to do is use ZRANGE by lex where start & stop are strings. I'm getting this error:

```
  File "/Users/kchonka/.pyenv/versions/new-test-lti1p3/lib/python3.9/site-packages/fakeredis/_server.py", line 82, in read_response
    raise response
redis.exceptions.ResponseError: min or max is not a float
```

On version 2.7.1

**Comment by kchonka** [comment]
I see there is support for ZRANGEBYLEX, but as of v6.2.0, this is deprecated and replaced with ZRANGE + BYLEX https://redis.io/commands/zrangebylex/

**Comment by cunla** [comment]
@kchonka, when would you be publish a PR for this?
