### ISSUE TITLE
Relax Python 3.8 version requirement

### ISSUE THREAD

**Issue by provinzkraut** [cunla/fakeredis-py#128]
**Is your feature request related to a problem? Please describe.**
Currently `fakeredis` requires Python `>=3.8.1`, which is incompatible with a lot of projects that have `>=3.8` as a requirement.

**Describe the solution you'd like**
Unless there is a specific reason to target this specific version, it would be great to change the requirement to `>=3.8`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cunla** [comment]
if I remember correctly, it is because of flake8 - but it is possible to change it to a dev dependency.

Do you want to change it?

**Comment by cunla** [comment]
See [here](https://github.com/python-poetry/poetry/issues/6171)

**Comment by provinzkraut** [comment]
@cunla Thanks for the quick fix!
