### ISSUE TITLE
Consider exposing the FakeRedisMixin

### ISSUE THREAD

**Issue by Redoubts** [cunla/fakeredis-py#129]
I want to use fakeredis, but we subclassed StrictRedis to do some additional things. It looks like mimicking what you do on our side, with something like

```
class FakeRedis(fakeredis._server.FakeRedisMixin, MyRedis):
    def __init__(self, *args, **kwargs):
        kwargs.pop("connection_pool", None) # SentinelConnectionPool shenanigans
        super().__init__(*args, **kwargs)
```

is perfect, but I feel bad reaching into `_server`. Can you consider exposing this as something to depend on?

**Comment by cunla** [comment]
If I understand correctly, you want to have a `connection_pool_class` parameter for `FakeRedis.__init__`?

**Comment by Redoubts** [comment]
Oh sorry, what I was asking was for __init__.py to also import FakeRedisMixin from _server

**Comment by cunla** [comment]
I am not sure I understand, can you provide details about the use case?

**Comment by cunla** [comment]
Thank you for the PR, but I would prefer to understand the need first.. perhaps write a test for it?

**Comment by Redoubts** [comment]
Sorry, I'm not sure I can describe the need more than I already have. Can you say what's not clear about the original comment?

**Comment by cunla** [comment]
Maybe write a sample code that necessitate exposing the mixin?

**Comment by cunla** [comment]
@Redoubts ?
