### ISSUE TITLE
Invalid input of type: 'QuerySet'

### ISSUE THREAD

**Issue by ValentinConstantin** [cunla/fakeredis-py#134]
Facing the following problem `redis.exceptions.DataError: Invalid input of type: 'QuerySet'. Convert to a bytes, string, int or float first.` in UnitTest (Django) when I try to set a cache `cache. Set(column, value)` with column type 'str' and value  type 'QuerySet Object'. Also, I would like to mention that with normal Redis everything works as I expected.

FakeRedis/FakeStrictRedis doesn't support value as QuerySet Object?

Tests starts following:
`   
with self.settings(CACHES= {'default': {'BACKEND': 'fakeredis.FakeRedis'}}):
`

**Comment by cunla** [comment]
No, `QuerySet` is a django object.
I am surprised this works on real redis.
