### ISSUE TITLE
Submit the latest version to Conda Forge

### ISSUE THREAD

**Issue by ilyanoskov** [cunla/fakeredis-py#137]
Dear Maintainers,

Could you please publish your package to Conda Forge as well? I have found a Pull Request that attempts to do this:

https://github.com/conda-forge/fakeredis-feedstock/pull/24

Thank you very much in advance.

**Comment by cunla** [comment]
I approached the feedstock maintainers, they are not active. I asked to be added to the repo - Let's see.
