### ISSUE TITLE
XREAD support

### ISSUE THREAD

**Issue by provinzkraut** [cunla/fakeredis-py#141]
**Is your feature request related to a problem? Please describe.**
I currently experience the problem of `XREAD` not being supported.

**Describe the solution you'd like**
I would like `XREAD` to be supported.

**Describe alternatives you've considered**
Not using fakeredis. There's not really an alternative here :grimacing: 

**Additional context**
I suppose there is a reason why this is currently not supported. @cunla maybe you can shed some light on this? I admit I'm not really familiar with the inner workings of this library, so I don't know the effort involved but if there's something I can help with let me know!

**Comment by cunla** [comment]
Hi,

I still need to implement this command in FakeRedis.

Are you interested in being involved? I wrote a guide on how to implement support for a command ([here](https://fakeredis.readthedocs.io/en/latest/guides/implement-command/)). All the stream commands are implemented in [this mixin](https://github.com/cunla/fakeredis-py/blob/master/fakeredis/commands_mixins/streams_mixin.py). It is important to write also tests for it to compare the results with real redis behavior.
