### ISSUE TITLE
FakeRedis doesn't support to be forked

### ISSUE THREAD

**Issue by tchapi** [cunla/fakeredis-py#146]
> **Note**
> 
> This is more of a question than a bug report

_First and foremost: thanks a lot for this library._

When using a library like [rq/rq](https://github.com/rq/rq) with a **FakeRedis** instance, an exception is raised since the fake Redis connection cannot be forked (at least that's my understanding).

**To Reproduce**

Here is a simple test file using the rq library, which, when used with the scheduler, creates a `Process` for it:

```python
from fakeredis import FakeStrictRedis
from rq.worker import Worker

fake_conn = FakeStrictRedis(version=6)
# from redis import Redis
# real_conn = Redis.from_url("redis://localhost:6379/0")

if __name__ == "__main__":
    Worker(
        ("default",),
        connection=fake_conn,
    ).work(with_scheduler=True)

```

This code works well if I use the `real_conn` Redis connection, or if I _don't_ use the scheduler (in which case, the worker does not fork upon start)

**Expected behavior**
Would there be a way to make the above code work "as expected" (ie, like a normal Redis connection)? I'm not sure if this would rather be a problem in rq/rq or in FakeRedis to be honest, so please bear with me if you think I should open an issue on the other side 🙇🏼 

Thanks a lot for your time
I'm available to test things if needed

**Platform:**

 - OS: `darwin`
 - python version: 3.10

**Additional context**

Here is the full error for what it's worth:
```

❯ python main.py
21:53:55 Worker rq:worker:c2c35ac0f0044a78b084254033c1c487 started with PID 43506, version 1.14.1
21:53:55 Subscribing to channel rq:pubsub:c2c35ac0f0044a78b084254033c1c487
21:53:55 *** Listening on default...
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    Worker(
  File "/lib/python3.10/site-packages/rq/worker.py", line 385, in work
    self._start_scheduler(burst, logging_level, date_format, log_format)
  File "/lib/python3.10/site-packages/rq/worker.py", line 471, in _start_scheduler
    self.scheduler.start()
  File "/lib/python3.10/site-packages/rq/scheduler.py", line 201, in start
    self._process.start()
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by cunla** [comment]
Hi,

fakeredis is "fake" :smile:. It is not connected to central storage, it keeps all data in Python process memory.
When forking the process, it would mean forking the entire storage, and changes made in one process are not captured in another (subscribing to a key in the worker process will not capture updates from the scheduler process).

So as long as you are working with FakeRedis within a single python process, all good. 

If you use rq with burst mode (which, for tests purpose, should be the way to use it), FakeRedis should work fine as rq does not create sub-processes.

**Comment by tchapi** [comment]
> If you use rq with burst mode (which, for tests purpose, should be the way to use it)

Indeed, that's the part I had not fully understood! thanks very much for the clear explanation 🙏🏼
