### ISSUE TITLE
is asyncio redis supported?

### ISSUE THREAD

**Issue by gerazenobi** [cunla/fakeredis-py#148]
I have the following code using `redis-py`:

```python

async def save_job_details(..., redis):
    #...
    async with redis.lock(redis_lock_key):
        pickled_value = await redis.hget("hash_name", activity_id)
        job_details = pickle.loads(pickled_value) if pickled_value is not None else None
        if some_logic(job_details):
            new_job_details = pickle.dumps({"job_id": job_id, "enqueue_time": enqueue_time})
            await redis.hset("hash_name", activity_id, new_job_details)
```

versions:
```
fakeredis          2.3.0
redis              4.4.0
```

When testing the method I pass an instance of `FakeStrictRedis()` and I get the following:

(1) the line `async with redis_client.lock(redis_lock_key):` throws the following:
>async with redis_client.lock(redis_lock_key):
E       AttributeError: __aenter__

(2) when removing the above-mentioned c.f. the async lock, I get this other error:
>pickled_value = await redis_client.hget(REDIS_LAST_JOB_DETAILS_HASH_NAME, activity_id)
E       TypeError: object NoneType can't be used in 'await' expression

Thanks in advance for any information here.

**Comment by cunla** [comment]
Hi,

- You are using quite an old version (2.3) - I recommend upgrading.
- As for async - it is supported, you need to use `aioredis.FakeRedis`. I updated the documentation.

Let me know if you have issues using `aioredis.FakeRedis`.

**Comment by gerazenobi** [comment]
@cunla thanks a lot for the rapid response !

>Let me know if you have issues using aioredis.FakeRedis.

No issues 👍
