### ISSUE TITLE
disconnect_on_error issue with Redis 4.5.5

### ISSUE THREAD

**Issue by alor** [cunla/fakeredis-py#149]
**Describe the bug**
tests are failing with: 
`FakeConnection.read_response() got an unexpected keyword argument 'disconnect_on_error'`
if redis 4.5.5 is used.

works fine if redis 4.5.4 is used.

this could be related to this change in Redis:
* Revert #2104, #2673, add `disconnect_on_error` option to `read_response()` (issues #2506, #2624)

**To Reproduce**
use redis version 4.5.5 in conjunction with fakeredis

**Comment by cunla** [comment]
This is already fixed in the code. I'll publish the new release this weekend
