### ISSUE TITLE
XREAD command returns empty list if count is bigger than number of messages

### ISSUE THREAD

**Issue by sveta-afanaseva** [cunla/fakeredis-py#256]
**Describe the bug**
Command XREAD returns empty list when COUNT is bigger than count of messages in stream. However, in redis python sdk it works another way (it returns all messages from the stream)

**Some proofs**
https://github.com/redis/redis-py/blob/emb-examples/doctests/dt_stream.py#L43
https://redis.io/docs/data-types/streams/

**To Reproduce**
1. Create FakeRedis object
2. Add message in stream with command xadd
3. Call xread command for your stream with argument count=100
4. Get empty list

**Expected behavior**
Expected list of all messages in stream

**Desktop (please complete the following information):**
 - OS: Windows
 - python version 3.10
 - redis-py version 5.0.1

**Comment by cunla** [comment]
Hi, can you provide the test for it? to run against real redis and fakeredis?

**Comment by sveta-afanaseva** [comment]
Yes, try this
```
from fakeredis import FakeRedis
from redis import Redis

def test_redis():
    fake_redis = FakeRedis()
    real_redis = Redis(host="localhost", port=6379)
    
    fake_redis.xadd("test", {"x": 1})
    real_redis.xadd("test", {"x": 1})
    
    res1 = fake_redis.xread(streams={"test": "0"}, count=100, block=10)
    res2 = real_redis.xread(streams={"test": "0"}, count=100, block=10)
    assert res1 == res2

```

**Comment by sveta-afanaseva** [comment]
Oh, sorry, it returns empty list, not None. My mistake
