### ISSUE TITLE
Implement support for `TOPK.RESERVE` (topk command)

### ISSUE THREAD

**Issue by cunla** [cunla/fakeredis-py#265]
Implement support for command `TOPK.RESERVE` in topk_mixin.py.

Initializes a TopK with specified parameters.

Here is the [Official documentation](https://redis.io/commands/topk.reserve/)

**Comment by andret13pinto** [comment]
Hey, I would like to work on this.

**Comment by cunla** [comment]
Hi, thanks for jumping in.
I started creating a skeleton for it [here](https://github.com/cunla/fakeredis-py/blob/topk/fakeredis/stack/_topk_mixin.py).

Feel free to fork and continue working on it, as I won't have time this month.

Let me know if you have any questions.

**Comment by andret13pinto** [comment]
@cunla sure will do. Was thinking of building a separate package for the HeavyKeeper datastructure, would you mind importing it, instead of adding it here as part of the source code?

**Comment by cunla** [comment]
See the file. I started implementing the HeavyKeeper class... 
not sure whether that class merit its own package.

**Comment by andret13pinto** [comment]
Ok. I will continue from there.

**Comment by cunla** [comment]
Do you have an ETA when you finish it?
I want to release a new version and it would be great if this is in it.

**Comment by andret13pinto** [comment]
1 to 2 week max

**Comment by cunla** [comment]
any update on this?

**Comment by andret13pinto** [comment]
Actually something came up that's impossibilating me to work on this. Sorry, maybe next time will be able to contribute 😄
