### ISSUE TITLE
FakeAsyncRedis stores state when clear instance expected.

### ISSUE THREAD

**Issue by irusland** [cunla/fakeredis-py#293]
**Describe the bug**
When creating FakeAsyncRedis each time we get same instance of redis. 

**To Reproduce**
```python
import asyncio

import fakeredis


async def main():
    redis_client_1 = fakeredis.FakeAsyncRedis()
    await redis_client_1.set('k', 'v')

    redis_client_2 = fakeredis.FakeAsyncRedis()
    v2 = await redis_client_2.get('k')

    assert v2 is None, f'Value of new redis is {v2}'


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
produces 
`AssertionError: Value of new redis is b'v'`

**Expected behavior**
Code runs successfully same as 
```python
import fakeredis


def main():
    redis_client_1 = fakeredis.FakeRedis()
    redis_client_1.set('k', 'v')

    redis_client_2 = fakeredis.FakeRedis()
    v2 = redis_client_2.get('k')

    assert v2 is None, f'Value of new redis is {v2}'


if __name__ == '__main__':
    main()
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4.1
 - python version: 3.10.12
 - redis-py version: aioredis==2.0.1, redis==5.0.1
 - full requirements.txt: aioredis==2.0.1, fakeredis==2.21.0, redis==5.0.1

**Additional context**
Not sure if it's an intended behaviour. But anyways I expect same behaviour as `FakeRedis`

**Comment by irusland** [comment]
Thanks for quick response! 

Could you please provide me an example? Or point out the necessary code in documentation?

**Comment by irusland** [comment]
Solved it with using different each time `port=faker.pyint()`

```python
import asyncio

import fakeredis
from faker import Faker

faker = Faker()


async def main():
    redis_client_1 = fakeredis.FakeAsyncRedis(port=faker.pyint())
    await redis_client_1.set('k', 'v')

    redis_client_2 = fakeredis.FakeAsyncRedis(port=faker.pyint())
    v2 = await redis_client_2.get('k')

    assert v2 is None, f'Value of new redis is {v2}'


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by cunla** [comment]
Yeah, that works.
It behaves the same as `redis.Redis` - by default the connection parameters are `localhost:6389`.
