### ISSUE TITLE
`FakeRedis.smembers()` reads data added to other instances (in version 2.21.2)

### ISSUE THREAD

**Issue by Zac-HD** [cunla/fakeredis-py#298]
**Describe the bug**
New instances of `FakeRedis()` read data added to older instances.  This is new in version 2.21.2, but a quick skim of https://github.com/cunla/fakeredis-py/compare/v2.21.1...v2.21.2 didn't show an obvious culprit.

**To Reproduce**
```python
from fakeredis import FakeRedis

for val in (b"1", b"2"):
    db = FakeRedis()  # <-- should be fresh each time!
    db.sadd(b"key", val)
    x = db.smembers(b"key")
    assert x == {val}, f"{x=} {val=}"
```
```python-traceback
Traceback (most recent call last):
  File "repro.py", line 7, in <module>
    assert x == {val}, f"{x=} {val=}"
AssertionError: x={b'2', b'1'} val=b'2'
```
(found by the https://github.com/HypothesisWorks/hypothesis/ test suite, minimized by hand)

**Comment by cunla** [comment]
Hi, this is not a bug. It aims to emulate redis behavior. When not supplying connection parameters - it will connect to "localhost:6389" server, which keeps a state.

This is [the relevant change](https://github.com/cunla/fakeredis-py/commit/b0bd6c786de95f008b729c260d7a880ccef32fde).

If you want a fresh instance, provide different connection parameters.

**Comment by Zac-HD** [comment]
Oh, I see!  That makes sense, but it'd be great to explain this in the changelog - I suspect I'm not going to be the only person to run into this.

Thanks for maintaining such a useful library 😊

**Comment by cunla** [comment]
Yes, you are right, someone already opened another similar issue.
Do you mind updating the changelog in a way that will be clear?

**Comment by Zac-HD** [comment]
https://github.com/cunla/fakeredis-py/commit/c0e620af93839f2761c8c0be2ecc6c531617ce0b looks good to me!
