### ISSUE TITLE
Type hint for version doesn't permit what the docs say to do

### ISSUE THREAD

**Issue by steve-mavens** [cunla/fakeredis-py#302]
**Describe the bug**

The docs say that the way to get Redis version 6 compatibility is to say `version=6`, but the type hint is `version: Tuple[int, ...] = (7,)`

Passing an integer does work, because `_create_version` handles ints, strings, or tuples. Again though its type hint is just the tuple.

It's quite verbose, but I think the correct type is `Union[Tuple[int, ...], int, str]`

If this is intentional, as a way to move people towards specifying the tuple, then fair enough and I withdraw my claim. Although in that case the docs should say to pass the tuple :-)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/302">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/302/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/302/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Right, I made it to support all cases.. I'll fix the type-hint.

**Comment by steve-mavens** [comment]
FYI, I think if you add enough strictness to mypy then with the old type hint it would have complained that `if isinstance(v, int)` introduces dead code, since it's "impossible". But of course making mypy stricter tends to be an exercise across the whole code base.

**Comment by steve-mavens** [comment]
Sorry, this still affects the async client. I don't think I have the power to re-open the issue.
