### ISSUE TITLE
Add better support for LUA scripts

### ISSUE THREAD

**Issue by JCHacking** [cunla/fakeredis-py#304]
**Is your feature request related to a problem? Please describe.**
I am trying to mock the redi backend for asgi-ratelimit and I am encountering the following error:
```python
Traceback (most recent call last):
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\commands\core.py", line 5172, in __call__
    return await client.evalsha(self.sha, len(keys), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\client.py", line 610, in execute_command
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\client.py", line 584, in _send_command_parse_response
    return await self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\client.py", line 631, in parse_response
    response = await connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\fakeredis\aioredis.py", line 171, in read_response
    raise response
redis.exceptions.NoScriptError: No matching script. Please use EVAL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\ratelimit\core.py", line 94, in __call__
    retry_after = await self.backend.retry_after(path, user, rule)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\ratelimit\backends\redis.py", line 51, in retry_after
    await self.lua_script(keys=list(ruleset.keys()), args=[json.dumps(ruleset)])
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\commands\core.py", line 5178, in __call__
    return await client.evalsha(self.sha, len(keys), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\client.py", line 610, in execute_command
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\client.py", line 584, in _send_command_parse_response
    return await self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\redis\asyncio\client.py", line 631, in parse_response
    response = await connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcmencia\PycharmProjects\NGCSQALIBS\py_api\venv\Lib\site-packages\fakeredis\aioredis.py", line 171, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_283a893bdb53a688600eff30001e6fb4e4ebd4f5): @user_script:?: [string "<python>"]:2: attempt to index a nil value (global 'cjson')
stack traceback:
	[string "<python>"]:2: in main chunk
```

**Describe the solution you'd like**
Add support for cjson? I don't know if this is only the problem.
I don't know exactly if this would be for lupa or for fakeredis, if you can give me some guidance I would appreciate it.

Related issues:
- https://github.com/jamesls/fakeredis/issues/25
- https://github.com/jamesls/fakeredis/issues/183

**Additional context**
I have tried this code:
```
from fakeredis.aioredis import FakeRedis
from fastapi import FastAPI
from ratelimit import RateLimitMiddleware, Rule
from ratelimit.backends.redis import RedisBackend
from ratelimit.types import Scope

app = FastAPI(debug=True)


async def authenticate(scope: Scope) -> tuple[str, str]:
    return str(scope["client"]), "default"


app.add_middleware(
    RateLimitMiddleware,
    authenticate=authenticate,
    backend=RedisBackend(
        FakeRedis.from_url("redis://redis")
    ),
    config={
        "": [Rule(minute=1)]
    }
)


@app.get("/")
async def test():
    return "A"
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/304">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/304/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/304/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Did you install fakeredis with lua support?
https://fakeredis.readthedocs.io/en/latest/#installation

**Comment by JCHacking** [comment]
> Did you install fakeredis with lua support?
> https://fakeredis.readthedocs.io/en/latest/#installation

Yes

**Comment by cunla** [comment]
I checked, to load `cjson`, it should be compiled for the machine where fakeredis is running.

I might add an environment variable `LUA_MODULES` stating which modules should be loaded.

**Comment by JCHacking** [comment]
So from what you say, to avoid this error I have to compile it on the machine that is going to run it with the environment variable LUA_MODULES=cjson right?

**Comment by cunla** [comment]
Well, I would need to implement this, but yeah, eventually, that would be the way it works.

**Comment by JCHacking** [comment]
I use poetry to manage dependencies, so when there is a whl uploaded to pypi it will download that one. I understand that in that case I will not use anything from LUA_MODULES because I will download it already compiled.

**Comment by cunla** [comment]
does cjson have a pypi package?

**Comment by JCHacking** [comment]
It seems that there are packages like [ujson](https://pypi.org/project/ujson/) that give this functionality (I have not tested them).

**Comment by cunla** [comment]
We need something where this would run:
```python
import lupa

lupa.LuaRuntime().execute("require('cjson')")
```

I don't think ujson meets this requirement

**Comment by JCHacking** [comment]
Trying with this code I get this error:
```python
lupa.lua54.LuaError: [string "<python>"]:1: module 'cjson' not found:
	no field package.preload['cjson']
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\lua\cjson.lua'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\lua\cjson\init.lua'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\cjson.lua'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\cjson\init.lua'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\..\share\lua\5.4\cjson.lua'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\..\share\lua\5.4\cjson\init.lua'
	no file '.\cjson.lua'
	no file '.\cjson\init.lua'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\cjson.dll'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\..\lib\lua\5.4\cjson.dll'
	no file 'C:\Users\jcmencia\AppData\Local\Programs\Python\Python312\loadall.dll'
	no file '.\cjson.dll'
stack traceback:
	[string "<python>"]:1: in main chunk
	[C]: in function 'require'
```

**Comment by JCHacking** [comment]
This is probably something that should be implemented in the lupa package.

**Comment by cunla** [comment]
lupa supports importing modules, it simply does not have cjson ootb.

I managed to install cjson:

- First, install [luarocks](https://luarocks.org) (I am using mac so `brew install luarocks`, but there is an installation for windows).
- Then, install cjson using `luarocks install lua-cjson`
- Then, copy `cjson.so` (or in your case I assume `cjson.dll`) to the project homedir.
- Then, the code I wrote should work.

**Comment by JCHacking** [comment]
I have been researching and there is a "cleaner" way to do this.
```python
import lupa

lupa.LuaRuntime().require("cjson")
```

**Comment by cunla** [comment]
Does it work without installing cjson first?

**Comment by cunla** [comment]
yeah, I am not sure why asgi-ratelimit chose to implement a ratelimit using a script that uses cjson - it seems a bit cumbersome.
But regardless, fakeredis now supports having LUA modules

**Comment by dvora-h** [comment]
@cunla Hi, I have the same issue, and I don't understand what the solution is - where should I add this code `lupa.LuaRuntime().require("cjson")`? and where to copy the cjson.so file?

**Comment by dvora-h** [comment]
This is the error I'm getting:
```
lupa.LuaRuntime().require("cjson")
lupa/lua54.pyx:502: in lupa.lua54.LuaRuntime.require
    ???
lupa/lua54.pyx:1835: in lupa.lua54.call_lua
    ???
lupa/lua54.pyx:1861: in lupa.lua54.execute_lua_call
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   lupa.lua54.LuaError: module 'cjson' not found:
E   	no field package.preload['cjson']
E   	no file '/usr/local/share/lua/5.4/cjson.lua'
E   	no file '/usr/local/share/lua/5.4/cjson/init.lua'
E   	no file '/usr/local/lib/lua/5.4/cjson.lua'
E   	no file '/usr/local/lib/lua/5.4/cjson/init.lua'
E   	no file './cjson.lua'
E   	no file './cjson/init.lua'
E   	no file '/usr/local/lib/lua/5.4/cjson.so'
E   	no file '/usr/local/lib/lua/5.4/loadall.so'
E   	no file './cjson.so'
E   stack traceback:
E   	[C]: in function 'require'
```

**Comment by cunla** [comment]
Shalom Dvora,

[Here is an explanation how to use it in fakeredis](https://fakeredis.readthedocs.io/en/latest/redis-stack/?h=lua#lua-binary-modules).

The gist:

```python
import fakeredis
r = fakeredis.FakeStrictRedis(lua_modules={"my_module.so"})
```

In terms of where to put cjson.so - You have in the stacktrace where LUA is looking for it. 
Note that lupa's LUA runtime is not your system's installed LUA runtime, e.g., if you are using luarocks and you have cjson.so in `$LUA_LIBDIR` - lupa won't search for it.

I recommend you add it to the project's working directory (`./cjson.so`) if you are sharing the code with others - that way, you can commit `cjson.so` in the root dir of the repo and when others pull they won't need to do extra configuration.

**Comment by cunla** [comment]
your code seems right. How do you run the tests? what is the working directory relative to where is cjson.so?

say the structure is:
```
./
./cjson.so
./tests
./tests/my_test.py
```

then if you are executing the test from `./` you should be fine. If you are running the test from `./tests/` then move cjson.so to that directory.

**Comment by dvora-h** [comment]
I run from tests directory, with pytest `pytest my_test.py::test_fake_redis` and my_test.py and cjson.so are both in the tests directory, I think this is how it should be, but I still have the error

**Comment by cunla** [comment]
... I am pretty sure the working directory you are running from is incorrect.

Try this:

Add to your test: `os.listdir()` to see whether `cjson.so` is there. 
- If it is not, then check which dir you are in in the python context and copy the file there.
- If it is, then from a python console, try running ([this is the source](https://github.com/scoder/lupa/blob/master/lupa/__init__.py)):
```python
import lupa
with lupa.allow_lua_module_loading()
     from lupa import lua54

lua = lua51.LuaRuntime()
lua.require('cjson')
```

If this gives the same error (and the file is there), it may be corrupted, or compiled for the wrong LuaRuntime version.

**Comment by cunla** [comment]
Up to you what you are trying to do. Redis is using [5.1](https://redis.io/docs/latest/develop/interact/programmability/eval-intro/).

You need to use the same version inside the `with` and outside.

**Comment by ItsDrike** [comment]
Would you be willing to simply patch in the support for cjson manually? I tired to do so myself, but I'm not very familiar with how you handle lua in the code-base, as this attempt only half-works:

<details>
<summary>Diff file for adding cjson.encode & decode support (wip)</summary>

```diff
diff --git a/fakeredis/commands_mixins/scripting_mixin.py b/fakeredis/commands_mixins/scripting_mixin.py
index 49a8a21..c6d852d 100644
--- a/fakeredis/commands_mixins/scripting_mixin.py
+++ b/fakeredis/commands_mixins/scripting_mixin.py
@@ -2,6 +2,7 @@ import functools
 import hashlib
 import importlib
 import itertools
+import json
 import logging
 import os
 from typing import Callable, AnyStr, Set, Any, Tuple, List, Dict, Optional
@@ -68,6 +69,41 @@ def _lua_redis_log(lua_runtime: LUA_MODULE.LuaRuntime, expected_globals: Set[Any
     LOGGER.log(REDIS_LOG_LEVELS_TO_LOGGING[lvl], msg)
 
 
+_lua_cjson_null = object()  # sentinel value
+
+
+def _replace_none_with_sentinel(obj: Any) -> Any:
+    """Recursively replace None with _lua_cjson_null in decoded JSON."""
+    if obj is None:
+        return _lua_cjson_null
+    if isinstance(obj, list):
+        return [_replace_none_with_sentinel(item) for item in obj]
+    if isinstance(obj, dict):
+        return {key: _replace_none_with_sentinel(value) for key, value in obj.items()}
+    return obj
+
+
+def _lua_cjson_encode(lua_runtime: LUA_MODULE.LuaRuntime, expected_globals: Set[Any], value: Any) -> str:
+    _check_for_lua_globals(lua_runtime, expected_globals)
+    print(value)
+    return json.dumps(value)
+
+
+def _lua_cjson_decode(lua_runtime: LUA_MODULE.LuaRuntime, expected_globals: Set[Any], json_str: str) -> Any:
+    _check_for_lua_globals(lua_runtime, expected_globals)
+    json_obj = json.loads(json_str)
+    json_obj = _replace_none_with_sentinel(json_obj)
+    print(json_obj)
+    if isinstance(json_obj, (dict, list)):
+        json_obj = lua_runtime.table_from(json_obj)
+    return json_obj
+
+
 class ScriptingCommandsMixin:
     _name_to_func: Callable[
         [
@@ -186,7 +222,7 @@ class ScriptingCommandsMixin:
         modules_import_str = "\n".join([f"{module} = require('{module}')" for module in self.load_lua_modules])
         set_globals = lua_runtime.eval(
             f"""
-            function(keys, argv, redis_call, redis_pcall, redis_log, redis_log_levels)
+            function(keys, argv, redis_call, redis_pcall, redis_log, redis_log_levels, cjson_encode, cjson_decode, cjson_null)
                 redis = {{}}
                 redis.call = redis_call
                 redis.pcall = redis_pcall
@@ -196,6 +232,12 @@ class ScriptingCommandsMixin:
                 end
                 redis.error_reply = function(msg) return {{err=msg}} end
                 redis.status_reply = function(msg) return {{ok=msg}} end
+
+                cjson = {{}}
+                cjson.encode = cjson_encode
+                cjson.decode = cjson_decode
+                cjson.null = cjson_null
+
                 KEYS = keys
                 ARGV = argv
                 {modules_import_str}
@@ -210,6 +252,9 @@ class ScriptingCommandsMixin:
             functools.partial(self._lua_redis_pcall, lua_runtime, expected_globals),
             functools.partial(_lua_redis_log, lua_runtime, expected_globals),
             LUA_MODULE.as_attrgetter(REDIS_LOG_LEVELS),
+            functools.partial(_lua_cjson_encode, lua_runtime, expected_globals),
+            functools.partial(_lua_cjson_decode, lua_runtime, expected_globals),
+            _lua_cjson_null,
         )
         expected_globals.update(lua_runtime.globals().keys())
```

</details>

The issue that I'm having here though is that for some reason, the table returned from `lua_runtime.table_from(json_obj)`  doesn't seem to support attribute access for the keys properly (e.g. `tbl.x` doesn't work even though the json_str was `'{"x": 1}'`, which did json-deserialize properly into python dict, and inspecting the keys of the returned lua table, the variable is in there, but the attribute access just doesn't seem to be working on it), which later causes issues in the actual lua script I tried this with, which uses that attribute access. I honestly have no idea why this happens, as when I tested this within a repl shell, it worked just fine:

```python
In [1]: from lupa import lua51
In [2]: lua = lua51.LuaRuntime()
In [3]: t = lua.table_from({'x': 1})
In[4]: t.x
Out[4]: 1
```

Which makes me really confused, since I know for a fact that `json_obj` before the `table_from` call was `{"x": 1}`. Maybe you're doing something weird that alters the behavior here?

Any feedback would be appreciated, I'm willing to PR this afterwards, or if you wish to add it yourself, I'm fine with you using the code above, it would be really nice to have this though, as I feel like cjson is something that people use really often with redis, and it's a shame that fakeredis doesn't support it.

---

Right now, the lack of basic cjson support makes testing for me a major pain, as I don't want to force contributors to install lua themselves and then luarocks, and then have it build lua-cjson. There's also no good way to script that, and the idea of shipping the so/dll inside of my repo is not something I like at all, I hate binary keeping blobs in general, but also, my code needs to work on multiple platforms, that includes linux (any kind), bsds, macos & windows, and I don't really feel like compiling cjson for all of those only to see some ABI breaking linux change make it not work anyways, so the suggested solution of using modules is really not something I love.

<details>
<summary>Need a quick solution better than module injection now?</summary>

In the absolute worst case, in case someone is in the same boat as me, I did think of one possibility which I might decide to do if the PR attempt fails here, which is to patch the exec calls and inject code by prepending whatever string script that was used, adding in something like dkjson (which is pure lua lib for json encoding/decoding) and mocking cjson to be an object that makes calls to dkjson stuff. E.g. adding something like this to `tests/conftest.py`:

```python
def _ensure_lua_modules() -> None:
    """Patch fakeredis to automatically load our custom lua scripts."""
    lua_pkgs_path = Path(__file__).parent / "lua_modules"
    lua_inject = textwrap.dedent(
        f"""
        package.path = package.path .. ";{lua_pkgs_path!s}/?.lua"

        _G.cjson = require("cjson-shim")
        """
    )
    # TODO: Patch the FakeRedis exec calls to inject this snippet before calling the original func

@pytest.hookimpl(tryfirst=True)
def pytest_sessionstart(session: pytest.Session) -> None:
    _ensure_lua_modules()
```

Then make a `tests/lua_modules/`, and add `cjson-shim.lua` there, with the following:

```lua
-- This is a cjson wrapper that uses dkjson in the back, but mostly behaves in a compatible way to cjson

json = require("dkjson")

local orig_encode = json.encode
local orig_decode = json.decode

json.encode = function(val)
  return orig_encode(val)
end

json.decode = function(str)
  local obj, _, err = orig_decode(str, 1, nil)
  if err then
    error(err)
  end
  return obj
end

json.null = nil -- dkjson uses nil/null fallback

return json
```

And finally, get `dkjson.lua` from https://raw.githubusercontent.com/LuaDist/dkjson/refs/heads/master/dkjson.lua

As you can see though, I haven't yet finished it, I'll update this snippet if I do, but I'd much prefer to get the proper support merged into this project instead.
</detail>
