### ISSUE TITLE
Reading multiple streams does not give expected result

### ISSUE THREAD

**Issue by mguijarr** [cunla/fakeredis-py#309]
**Describe the bug**

When reading multiple streams, if `block` is set `fakeredis` stops at the first stream whereas the real Redis
gives output for all streams as expected.

**To Reproduce**

```python
import redis
from fakeredis import FakeServer, FakeStrictRedis

def main():
    fake_server = FakeServer()
    fake_client = FakeStrictRedis(server=fake_server)
    real_client = redis.Redis(host="localhost", port=6379, db=1)

    k = "key"
    k2 = "key2"
    streams = {k: "0", k2: "0"}

    real_client.xadd(k, {"value":1234})
    real_client.xadd(k2, {"value": 5678})
    res = real_client.xread(streams, block=200)
    assert len(res) == 2
    print("Success: read 2 streams", res)

    fake_client.xadd(k, {"value":1234})
    fake_client.xadd(k2, {"value": 5678})
    res = fake_client.xread(streams, block=200)
    assert len(res) == 2, "Could not read 2 streams"
```

**Expected behavior**

Expected behaviour: the assertion should not raise, `res` for `fake_client` should be the same as `res` for `real_client`

It can be narrowed down in file `fakeredis/commands_mixins/streams_mixin.py` in method `_xread`:

```python
...
for stream_name, start_id in stream_start_id_list:
            item = CommandItem(stream_name, self._db, item=self._db.get(stream_name), default=None)
            stream_results = self._xrange(item.value, start_id, max_inf, False, count)
            if len(stream_results) > 0:
                res.append([item.key, stream_results])
            if first_pass and (count is None): ###
                return res                                    ### why the early exit ? there might be other items in list
...
```
Note: when removing `block` in `fake_client.xread` in the example above, it seems to work ❓ 🤔 (except that in real life the code really needs `block`) 

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - python version 3.11
 - redis-py version 5.0.1
 - fakeredis 2.23.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/309">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/309/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/309/pledge.svg">
</picture>
</a>

**Comment by mguijarr** [comment]
Thanks @cunla 👍🏻

**Comment by mguijarr** [comment]
I would like to know if there is going to be a new release with this bug fix soon? And thanks again! The simplified version looks nice 👍🏻

**Comment by cunla** [comment]
This or next weekend
