### ISSUE TITLE
TTL returns -2 (not found) for empty streams

### ISSUE THREAD

**Issue by Eugeny** [cunla/fakeredis-py#313]
STR:

```python
fake_redis.xadd(self.stream_name, {'x': 1})
fake_redis.expire(self.stream_name, 60 * 60 * 24 * 365 * 99)
assert fake_redis.keys(self.stream_name) 
fake_redis.ttl(self.stream_name) # is -2
```

Python 3.10
redis-py==4.5.4
fakeredis==2.23.2

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/313">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/313/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/313/pledge.svg">
</picture>
</a>

**Comment by Eugeny** [comment]
Upon further investigation this is due to `if (not key...) return` in `_expireat`, whose `__bool__` then checks for `bool(self._value)` which is `False` because `XStream.__len__` is 0

**Comment by cunla** [comment]
Thanks for reporting this. Do you want to work on a fix and submit a PR (since you already did the hard part)?

Otherwise, I will work on it this weekend;

**Comment by Eugeny** [comment]
I'm not actually sure what the purpose of the `if not key` check in `_expireat` is so I would prefer not to risk breaking anything by not knowing the library, I literally just started using it today :D

**Comment by cunla** [comment]
No prob, I'll have a look at it later this week.
Thanks again for reporting

**Comment by cunla** [comment]
fixed

**Comment by Eugeny** [comment]
Thank you!
