### ISSUE TITLE
`random` entropy globally reduced for all importers

### ISSUE THREAD

**Issue by Redoubts** [cunla/fakeredis-py#315]
**Describe the bug**
https://github.com/cunla/fakeredis-py/blob/5240b69b13160584b6f9ed748dbc8843427b3671/fakeredis/stack/_topk_mixin.py#L13

This line has call which globally sets the seed for all users of `random`, and this happens at import time for users of fakeredis. Is this needed? If so, can this module create its own generator for internal use? https://docs.python.org/3/library/random.html#random.Random

**Expected behavior**
Side-effect free imports

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/315">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/315/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/315/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Makes sense. I'll publish an update.
