### ISSUE TITLE
Change in redis-py v5.0.8 causes strange behavior in fakeredis-py

### ISSUE THREAD

**Issue by x0ul** [cunla/fakeredis-py#316]
**Describe the bug**
* Using python 3.12.4
* Bug appears in fakeredis-py v2.23.4 when redis-py is v5.0.8 (offending commit found via bisect https://github.com/redis/redis-py/commit/e7ef54a0aeb55accc14b72f4faef5fc2e4c9a780)
* Bug does not occur running the same test with real redis server (7.2.5) and redis-py (v5.0.8)

fakeredis-py returns unexpected values for `get` that appear to be left over results from the previous command

**To Reproduce**

Run the following test case with pytest

```python
    @pytest.mark.asyncio
    async def test_cause_fakeredis_bug():
        redis = fakeredis.FakeAsyncRedis()
    
        async def worker_task():
            await redis.rpush("list1", "list1_val")
            assert await redis.blpop("list2") == (b"list2", b"list2_val")
            await redis.set("foo", "bar")
    
        async with asyncio.TaskGroup() as tg:
            tg.create_task(worker_task())
            assert await redis.blpop("list1") == (b"list1", b"list1_val")
            await redis.rpush("list2", "list2_val")
    
        # await redis.get("foo")  # uncomment to make test pass
>       assert await redis.get("foo") == b"bar"
E       AssertionError: assert b'OK' == b'bar'
E         
E         At index 0 diff: b'O' != b'b'
E         
E         Full diff:
E         - b'bar'
E         + b'OK'
```

**Expected behavior**
Test passes. This test passes with redis-py v5.0.7.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: `Linux 6.10.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000 x86_64 GNU/Linux`
 - python version: 3.12.4
 - redis-py version: v2.23.4
 - full requirements.txt?

**Additional context**
Doing another `get` (see commented-out line in test case above) seems to re-sync the connection and cause the test to pass.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/316">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/316/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/316/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
I am surprised this is the first time this was mentioned. Anyway, should be fixed.

**Comment by x0ul** [comment]
Thanks so much for the quick fix, I seriously appreciate what this library has helped me do. [Was removing this call to `put_response` the main change?](https://github.com/cunla/fakeredis-py/pull/317/commits/dd5946587403dc49ff64755c14e62550a8c87f50#diff-e90887aa6a8a49ef42fda77ab4013237d622f8a79972df7ac5413d736fa1a782L67)

**Comment by cunla** [comment]
yes, it is writing the response a few lines afterwards in the `finally` section
