### ISSUE TITLE
typing_extensions in dependencies should be typing-extensions

### ISSUE THREAD

**Issue by M1ha-Shvn** [cunla/fakeredis-py#330]
**Describe the bug**
Not a bug, in reality, but lead to confusion in my case.

`importlib.metadata.distribution` shows `typing_extensions` requirement as `typing_extensions (>=4.7,<5.0) ; python_version < "3.11"'`.
The correct name of the library is `typing-extensions` (I get it as it is written on [pypi](https://pypi.org/project/typing-extensions/)). This may lead to some confusions in scripts which analyze dependencies as `Requirement("typing_extensions")` is not equal to `Requirement("typing-extensions")` (nevertheless, both work and are installed correctly by pip).

**To Reproduce**
```python
from importlib.metadata import distribution
from packaging.requirements import Requirement

dist = distribution("fakeredis")
for req in dist.requires:
    print(Requirement(req).name)
```

**Expected behavior**
library name should be typing-extensions

**Desktop (please complete the following information):**
 - OS: docker python-3.9-slim
 - python 3.9 (but can be any other)
 - fakeredis[lua]==2.24.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/330">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/330/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/330/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for reporting this. Do you mind creating a PR for this change? (also run `poetry update` to update poetry.lock)

**Comment by cunla** [comment]
Nevermind, I got it
