### ISSUE TITLE
When trying to install with `pip install fakeredis[json]`, pip reports `no matches found`

### ISSUE THREAD

**Issue by nelson-kiwi** [cunla/fakeredis-py#351]
**Describe the bug**
It is not quite a bug, however I can't reach the specific extra option.

**To Reproduce**
1. Go to your terminal
2. Load your virtual environment
3. run: `pip install fakeredis[json]`

**Expected behavior**
An installation report for the extra option.

**Screenshots**
<img width="731" alt="image" src="https://github.com/user-attachments/assets/8ce961c3-4666-40c0-b008-97a802f94c8c" />

**Desktop (please complete the following information):**
 - OS: Mac OS Sequoia 15.1.1
 - python version: Python 3.10
 - redis-py version: 5.0.1
 - fakeredis-py version: 2.26.1

**Additional context**
I'm working on a MacBook Air 2024:
 - Processor: Apple M3
 - RAM: 16 GB

**Comment by cunla** [comment]
pip install "fakeredis[json]"

**Comment by nelson-kiwi** [comment]
Please update your docs, I ran the commands as you suggested.

<img width="731" alt="image" src="https://github.com/user-attachments/assets/7efd3ca4-0f23-44f1-ba00-e4c7640d99ca" />

**Comment by cunla** [comment]
linux vs. mac...
