### ISSUE TITLE
Pottery RedisDict compatibility 

### ISSUE THREAD

**Issue by mchlbatista** [cunla/fakeredis-py#48]
**Describe the bug**
`pottery.RedisDict` requires `host` as part of `connection_pool.connection_kwargs`.
https://github.com/brainix/pottery/blob/c7be6f1f25c5404a460b676cc60d4e6a931f8ee7/pottery/base.py#L90

**To Reproduce**
Create a `pottery.RedisDict` using an instance of `fakeredis`.

**Solution**
The solution already tested is to add `host` to this `list`
https://github.com/cunla/fakeredis-py/blob/1e4bddb1f783bd566d9a61c008588aa0264600d1/fakeredis/_server.py#L130

_I could make the change and create the PR if that helps in any way_

Thanks!

**Comment by cunla** [comment]
Hi, please go ahead and create a PR
