### ISSUE TITLE
python-six dependency

### ISSUE THREAD

**Issue by pgajdos** [cunla/fakeredis-py#50]
**Describe the bug**
Am I right that python-six dependency could be removed?

**Comment by cunla** [comment]
It is used in `_basefakesocket.py`.

**Comment by cunla** [comment]
@pgajdos is that an issue?

**Comment by pgajdos** [comment]
Well depends on how you look at it. You do not seem to support python 2 anymore and  [Six is a Python 2 and 3 compatibility library. ](https://six.readthedocs.io/) From that one could deduce that six is not needed anymore.

**Comment by mcochner** [comment]
Please note that six is still also used in https://github.com/cunla/fakeredis-py/blob/master/fakeredis/_fakesocket.py#L10
