### ISSUE TITLE
Difference in `get` compared to real Redis

### ISSUE THREAD

**Issue by dhruvkb** [cunla/fakeredis-py#58]
**Describe the bug**
When using Django cache with a Redis backend, the `get()` call returns an int if the value stored is an integer. FakeRedis returns a byte string for the same `get()` call.

**Expected behavior**
If the value stored is an integer (as can be confirmed with `.incr()`) the returned value should be an int rather than a byte string.

**Screenshots**

<img width="362" alt="Screenshot 2022-10-19 at 9 20 29 AM" src="https://user-images.githubusercontent.com/16580576/196603861-ad764b96-7861-4b6e-bc46-bc10246cf88f.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Python version: 3.10.8
 - Packages:
   - django-redis==5.2.0
   - fakeredis==1.9.3
   - redis==4.3.4

**Comment by cunla** [comment]
I implemented a test in the branch above to compare the behavior of Redis and FakeRedis.
`django-redis` does the decode part: https://github.com/jazzband/django-redis/blob/master/django_redis/client/default.py#L265
