### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by lsmith77** [cunla/fakeredis-py#61]
**Is your feature request related to a problem? Please describe.**

Going by https://github.com/cunla/fakeredis-py/blob/master/pyproject.toml#L23 the project seems to be `BSD-3-Clause` but https://github.com/cunla/fakeredis-py/blob/master/LICENSE creates some confusion.

**Describe the solution you'd like**
Could the references to individuals be moved to a file COPYRIGHT and the LICENSE file just include the BSD-3-Clause?

**Additional context**
I am trying to automate an overview of the licenses included in my projects and currently I cannot detect the license using dependabots database.

**Comment by lsmith77** [comment]
IANAL but it seems to be accepted to re-license MIT code under a BSD license:
https://opensource.stackexchange.com/questions/7673/can-i-take-mit-licensed-code-and-distribute-it-under-bsd

From what I can tell you copied individual code from `redis-py` rather than including full source files, which makes this all the more complicated since I am unsure how to attribute properly then.

Another option could be to look into moving your code to the MIT license but this could be too cumbersome.

Not sure if it is feasible to remove the `redis-py` code and pull it in as a dependency which would be the cleanest solution from a legal point of view.

**Comment by cunla** [comment]
I cannot change the license as I adopted the package a few months ago (See years).
I can add `---------` line between the licenses like the [pandoc](https://github.com/jgm/pandoc/blob/2.5/COPYRIGHT) linked in the stackexchange question you posted.

**Comment by lsmith77** [comment]
Unfortunately GitHub seems unable to detect the license for pandoc as well :-/

**Comment by cunla** [comment]
I can't remove the license. It was there before my time.

**Comment by lsmith77** [comment]
yeah .. I guess not much to do here without creating a gigantic amount of work (which might never work out) to try and find all the contributors to agree to align the licenses.

so closing the ticket.
