### ISSUE TITLE
Implementing A Currently Unimplemented Command

### ISSUE THREAD

**Issue by the-wondersmith** [cunla/fakeredis-py#64]
@cunla  First, **huge** thanks for maintaining the repo to begin with.

Second, can I ask for a little guidance on the "correct" way to add an implementation for a currently unimplemented command? The application whose test suite we're using `fakeredis-py` in uses `zmscore` in a few critical places, so I've had to implement a functional standin for it and sort of monkey-patch it into `fakeredis-py` as part of the test setup. It's not a huge deal at all, but it seems silly to not contribute the implementation to the `fakeredis-py` repo.

I _did_ take a look at the repo itself, but very quickly got confused as to where exactly a given `COMMAND` is "fulfilled" by a given callable / function. I'd be _more_ than happy to make a PR if you'd give me the quick and dirty how-to on adding a new command. 

For reference, this is the implementation of `zmscore` I worked out:

```python
from __functools__ import annotations
from typing import Any, Iterable
import fakeredis


def zmscore(self: fakeredis.FakeRedis, key: str | bytes, members: Iterable[Any]) -> tuple[float, ...]:
    """A functional stand-in for Redis's `zmscore` function."""
    pipe = self.pipeline()

    for member in members:
        member = member if isinstance(member, bytes) else str(member).encode()
        pipe.zscore(name=str(key), key=member)

    return tuple(pipe.execute())
```

**Comment by cunla** [comment]
Hi, thanks for this. I think I will make it also into a guide in the contributing part in the readme.

### Implementing the command 
Creating a new command support should be done in the `FakeSocket` class by creating the method and using `@command` decorator (which should be the command syntax, you can use existing samples on the file).

For example:
```
    @command((Key(ZSet), bytes))
    def zscore(self, key, member):
        try:
            return self._encodefloat(key.value[member], False)
        except KeyError:
            return None
```

### Implement a test for it
There are multiple scenarios for test, with different versions of redis server, redis-py, etc.
The tests not only assert the validity of output but runs the same test on a real redis-server and compares the output to the real server output.

- Create tests in the `test_fakeredis6.py` if the command is supported in redis server 6.x.
- Alternatively, create the test in `test_fakeredis7.py` if the command is supported only on redis server 7.x.
- If support for the command was introduced in a certain version of redis-py (see [redis-py release notes](https://github.com/redis/redis-py/releases/tag/v4.3.4)) you can use the decorator `@testtools.run_test_if_redispy_ver` on your tests. example:
```
@testtools.run_test_if_redispy_ver('above', '4.2.0') # This will run for redis-py 4.2.0 or above.
def test_expire_should_not_expire__when_no_expire_is_set(r):
    r.set('foo', 'bar')
    assert r.get('foo') == b'bar'
    assert r.expire('foo', 1, xx=True) == 0
```

**Comment by the-wondersmith** [comment]
@cunla Baller, thank you! I'll open a PR as soon as I'm able.

While I have your attention though, I've just run into another potentially related issue - does `fakeredis` not support [Redis's JSON commands](https://redis-py.readthedocs.io/en/stable/redismodules.html#redisjson-commands)? If not, I'd be happy to add them too, but I think I'd want your input on whether they should _also_ go in the `_fakesocket` module or if they should live in their _own_ module.

**Comment by cunla** [comment]
Hi @the-wondersmith, thanks the initiative.

Regarding JSON commands:
I started breaking down all the commands to mixins under `command_mixins` directory.
I think we would want to have it as a mixin like `redis-py` does it (see [here](https://github.com/redis/redis-py/blob/master/redis/commands/redismodules.py)) and then have `FakeRedis` inherit from the mixin

**Comment by the-wondersmith** [comment]
@cunla Even more better. I'll probably be opening *two* PRs then, the second of which will get the JSON mixin at least started.

**Comment by the-wondersmith** [comment]
@cunla  I'm having a _TON_ of trouble figuring out the correct way to apply the `@command` decorator for `ZMSCORE`.

The redis docs have its signature as `ZMSCORE key member [member ...]`. I've implemented it in Python compatibly with the redis-py implementation, so it's calling signature is `def zmscore(self, key: str, members: list[str | bytes]) -> tuple[float, ...]`.

Can you give me a little guidance here? What's the proper `@command` decorator for ^ _that_?

**Comment by cunla** [comment]
@the-wondersmith ,

`BZPOPMAX` is kind of similar, with a syntax of `BZPOPMAX key [key ...] timeout`. So you can use it as a reference:
```
    @command((bytes, bytes), (bytes,), flags='s')
    def bzpopmax(self, *args):
        keys = args[:-1]
        timeout = Timeout.decode(args[-1])
```
Notice the method signature should have generic `*args` and then the parsing (and raising errors) should be inside (so fakeredis is also compatible with the errors it raises)

It should be something like:
```
@command((Key(ZSet), bytes, bytes), (bytes))
def zmscore(self, key, *args):
```

**Comment by the-wondersmith** [comment]
@cunla Thank you! I ended up bashing my head against it until I eventually ended up with something that worked. Final implementation is:

```python
@command(name="zmscore", fixed=(Key(ZSet), bytes), repeat=(bytes,))
def zmscore(self, key: str, *members: Union[str, bytes]) -> list[Optional[float]]:
    """Get the scores associated with the specified members in the sorted set stored at key.
    For every member that does not exist in the sorted set, a nil value is returned."""
    members = (
        mbr
        if isinstance(
            mbr,
            bytes,
        )
        else str(mbr).encode()
        for mbr in members
    )

    scores = itertools.starmap(
        self.zscore,
        zip(itertools.repeat(key), members),
    )

    return list(scores)
    ```

I'm working on the associated tests and should have a PR for you later this afternoon. I've got the JSON mixin started too, and should have that PR-ready not too long afterwards.

Hypothetically, if I were to say... temporarily lose my mind and go through the entire codebase and apply type annotations and docstrings throughout, would that be a problem?

**Comment by cunla** [comment]
Wait with the type annotations. Keep in mind the library needs to support python 3.7+ (I think in python 3.7 you should use `import typing` - not sure when it was introduced that you can use `list[str]`).

I appreciate the eagerness, but I am working on v2 at the same time which will break it into smaller files and hopefully make it easier to make changes.

Use the github actions to see that it works for different versions of redis server, redis-py and python.

**Comment by the-wondersmith** [comment]
@cunla I've got all the tooling configured to enforce `python = ">=3.7.2,<3.11"` at the moment. As to when support for `list[str]` was introduced, adding `from __future__ import annotations` will ensure that works as expected in 3.7+.

Also uhhh... too late? I was left alone for longer than 15 seconds and I'm already a good chunk of the way through cleanup. 😅

If you'd like, pop me an email. I'd _love_ to help out with v2, if you'll have me. My email is the same as my username with `@` instead of the `-`, (tld is `.dev`).

**Comment by cunla** [comment]
Happy to have you join me in maintaining it.
I will write you an email

**Comment by the-wondersmith** [comment]
@cunla [As promised](https://github.com/cunla/fakeredis-py/pull/67) 😁
