### ISSUE TITLE
Implement Support For RedisJSON Commands

### ISSUE THREAD

**Issue by the-wondersmith** [cunla/fakeredis-py#70]
[Implement support](https://github.com/the-wondersmith/fakeredis-py/tree/json-support) for [RedisJSON](https://redis.io/docs/stack/json/) using the new [mixin pattern](https://github.com/cunla/fakeredis-py/issues/68).

**Comment by the-wondersmith** [comment]
@cunla Please mark this as a chore and assign it to me

**Comment by the-wondersmith** [comment]
@cunla I've completed the initial (read: bare minimum) work to get JSON support going. I sent you an email about tagging up to continue our conversation about how we wanted to breakup the various [modules](https://redis.io/resources/modules/) and start folding in support for modules that aren't _currently_ supported.

Just adding this post here for visibility and accountability 😅

**Comment by gabrielcnr** [comment]
Just found about `fakeredis-py` but my code uses `.json()` API. Do you need help with this issue?

**Comment by the-wondersmith** [comment]
@gabrielcnr Would love a hand! If you'd like, all the current work is being done on the [initial-json-support](https://github.com/the-wondersmith/fakeredis-py/tree/initial-json-support) branch on my fork. As it stands support has been (partially) implemented for

- `JSON.DEL`
- `JSON.GET`
- `JSON.SET`

but every supported JSON command has a command-decorated method in the JSON command mixin class. (e.x. [`JSON.RESP`](https://github.com/the-wondersmith/fakeredis-py/blob/initial-json-support/fakeredis/commands_mixins/json_mixin.py#L262)). The unimplemented commands _probably_ don't have the proper `command` signature, but the method arguments come straight from redis-py so those _are_ correct.

The unit tests have been pulled over from the official [`redis-py`](https://github.com/redis/redis-py/blob/master/tests/test_json.py) repo and the necessary changes have been made to make them compatible with the `fakeredis-py` test suite. All of the tests that target JSON commands that aren't currently implemented have been marked `xfail`. 

If you'd like to lend a hand, please feel free to pick any number of unimplemented functions and make PRs against that branch with their proper implementations 😁.

**Comment by the-wondersmith** [comment]
@gabrielcnr If you're still interested in lending a hand with JSON command support, would you email me? My email is the same as my username with `@` instead of the `-`, (tld is `.dev`).
