### ISSUE TITLE
commands to modify sets have different signature then official redis client.

### ISSUE THREAD

**Issue by klausmyrseth** [cunla/fakeredis-py#86]
**Describe the bug**
Signature in fakeredis dont match normal redis client for set commands, srem in particular.

from fakeredis import FakeRedis
r = FakeRedis()
r.srem(name='somekey', values='one')

This crash with values does not exist, and I check the signature and members is there instead for fakeredis that is.

Workaround is to use r.srem('somekey', 'one') which I really dont like.

**To Reproduce**
just run the codesample above

In fakeredis the values field is called members, this needs to be updated.

**Expected behavior**
I expect the codesample above to work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - python version 3.10.8
 - redis-py version 4.3.5
 - full requirements.txt (were using pypi but its about the same)
geojson = {version="*", index="pypi"}
aiohttp = {version="*", index="pypi"}
StrEnum = {version="*", index="pypi"}
python-json-logger = {version="*", index="pypi"}
google-cloud-datastore = {version="*", index="pypi"}
google-cloud-bigquery = {version="*", index="pypi"}
redis = {version="*", index="pypi"}
sanic = {version="*", index="pypi"}
sanic-gzip = {version="*", index="pypi"}

**Additional context**

**Comment by cunla** [comment]
Are there more commands like that or only this one?

**Comment by cunla** [comment]
Not sure how you got it to work with real redis - The [method signature](https://github.com/redis/redis-py/blob/fb647430f00cc7bb67c978e75f2dabc661567779/redis/commands/core.py#L3330) is:
```python
def srem(self, name: str, *values: FieldT) -> Union[Awaitable[int], int]:
```
so running the command you propose does not work on redis-py and therefore does not work on FakeRedis

**Comment by klausmyrseth** [comment]
No you have to send string by string, my mistake, I have a unit test now that works on my side for my case. Ill update my sample.

We only met srem as an issue, havent dug hard into the other commands.

**Comment by cunla** [comment]
please send the test that does not work

**Comment by klausmyrseth** [comment]
def test_fail():
  from fakeredis import FakeRedis
  r = FakeRedis()
  r.srem(name='somekey', values='one')

**Comment by cunla** [comment]
Did you try it with real `redis-py`?
It fails on real `redis-py` as well with the same error...

**Comment by klausmyrseth** [comment]
I located the source of the bug on my side, its most likely in my venv I was using not the libraries or some editor cache in the venv....

Sorry to bug everyone, for some reason it showed different signatures when using the classes directly and that crashed in my unit tests when I used this. I recreated a clean venv with only the usecase and the two libs redis and fakeredis and now the signatures are similar and it works as expected. I will try find what is messing up my environment without bugging you guys :)

**Comment by cunla** [comment]
No problem @klausmyrseth. Happy to help.
